id = "hytale-test"
name = "Hytale Test"
type = "HYTALE"

[environment]
image = "itzg/minecraft-server"
memory-amount="1024"
EULA = "TRUE"
MEMORY = "1G"
ONLINE_MODE = "TRUE"
MOTD = "Hytale Test Server"

[[volumes]]
id = "world"
target_folder = "/data"
